### ISSUE TITLE
Compatible with Leaflet 1.0?

### ISSUE THREAD

**Issue by tdaubs** [kartena/Leaflet.zoomslider#66]
Is this plugin compatible with Leaflet 1.0?

**Comment by ajmendez** [comment]
To answer this really old question:  As of this post, zoomslider works with V1.0.0-rc.1 and leaflet V1.0.3 (most current version).

**Comment by perliedman** [comment]
:+1: Thanks for notifying!

**Comment by ventralnet** [comment]
Be aware zoomslider has a dependency on v0.7.7 in its package.json file if you are using npm and a module loader.
