### ISSUE TITLE
Leaflet and NPM

### ISSUE THREAD

**Issue by ventralnet** [kartena/Leaflet.zoomslider#68]
This is less of a bug and more of an annoyance I suppose. It looks like your library is dependent on Leaflet v0.7.7.  I am working on a leaflet upgrade to v1.0.3.  NPM will bring in both versions of leaflet.js.  This causes issues since leaflet sets some global namespace types.  

For example, in my app this is happening....
leaflet v1.0.3 is being imported, later in the code leaflet draw is imported which adds to L.Control a draw property (L.Control.Draw). Then zoomslider is imported, which subsequently imports its version of leaflet v0.7.7 which reinitializes the L.Control object eliminating what the leaflet draw plugin initialized.

Could you maybe look at moving leaflet.js to a dev dependency, or updating your dependency version to the recent leaflet if everything works?

**Comment by pthorin** [comment]
I have now published version 0.7.1 which does not depend on leaflet.
