### ISSUE TITLE
Move zoomslider.option.position to option!

### ISSUE THREAD

**Issue by KarelWintersky** [kartena/Leaflet.zoomslider#71]
default is 'topleft' 
we must can change this position!

**Comment by pthorin** [comment]
It is already an option, and you can change it as such.

**Comment by KarelWintersky** [comment]
Please, write more detailed readme

**Comment by keyjote** [comment]
@KarelWintersky, as this is an open source project, pull requests with improvements are welcomed.
Improving the readme can be your collaboration to this project.
